services:
  app:
    image: php:8.3-apache
    container_name: php-app
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "chown -R www-data:www-data /var/www/html &&
              chmod -R 755 /var/www/html &&
              apt-get update &&
              apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev &&
              docker-php-ext-configure gd --with-freetype --with-jpeg &&
              docker-php-ext-install gd pdo pdo_mysql &&
              apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pool
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
